version: '3'
services:   
  app:
      container_name: nginx-react      
      restart: always      
      build:   
        context: .
        dockerfile: ./Dockerfile
      ports:         
        - '3000:3000'